-- MySQL Script generated by MySQL Workbench
-- Mon May 30 08:44:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Film_Base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Film_Base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Film_Base` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Film_Base` ;

-- -----------------------------------------------------
-- Table `Film_Base`.`FilmIformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`FilmIformation` (
  `idFilmIformation` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(35) NOT NULL,
  `Data_de_sortie` DATE NOT NULL,
  `Duree` TIME NOT NULL,
  `Realisateur` VARCHAR(25) NOT NULL,
  `idClients` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idFilmIformation`),
  INDEX `idClients_idx` (`idClients` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Film_Base`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`Clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `idFilmIformation` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idClients`),
  CONSTRAINT `idFilmIformation`
    FOREIGN KEY (`idFilmIformation`)
    REFERENCES `Film_Base`.`FilmIformation` (`idFilmIformation`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Film_Base`.`Films_Loues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`Films_Loues` (
  `idIntermediaire_table` INT NOT NULL AUTO_INCREMENT,
  `Data_de_Location` DATETIME NOT NULL,
  `Date_de_Retour` DATETIME NOT NULL,
  PRIMARY KEY (`idIntermediaire_table`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Film_Base`.`Date_de_Creation_et_Modification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`Date_de_Creation_et_Modification` (
  `idDate_de_Creation_et_Modification` INT NOT NULL AUTO_INCREMENT,
  `Date_de_Creation` DATETIME NOT NULL,
  `Derniere_Date_de_Modification` DATETIME NOT NULL,
  `Films_Loues_idIntermediaire_table` INT NOT NULL,
  PRIMARY KEY (`idDate_de_Creation_et_Modification`, `Films_Loues_idIntermediaire_table`),
  CONSTRAINT `fk_Date_de_Creation_et_Modification_Films_Loues1`
    FOREIGN KEY (`Films_Loues_idIntermediaire_table`)
    REFERENCES `Film_Base`.`Films_Loues` (`idIntermediaire_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Film_Base`.`FilmCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`FilmCategories` (
  `idFilmCategories` INT NOT NULL AUTO_INCREMENT,
  `Action` VARCHAR(45) NOT NULL,
  `Comedie` VARCHAR(45) NOT NULL,
  `Aventure` VARCHAR(25) NOT NULL,
  `Drame` VARCHAR(25) NOT NULL,
  `Horreur` VARCHAR(25) NOT NULL,
  `Autre` VARCHAR(25) NOT NULL,
  `idFlimIformation` INT NOT NULL,
  PRIMARY KEY (`idFilmCategories`),
  CONSTRAINT `idFlimIformation`
    FOREIGN KEY (`idFlimIformation`)
    REFERENCES `Film_Base`.`FilmIformation` (`idFilmIformation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Film_Base`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`Payments` (
  `idPayments` INT NOT NULL AUTO_INCREMENT,
  `Date_de_payment` DATETIME NOT NULL,
  `Description` VARCHAR(25) NOT NULL,
  `Montant` VARCHAR(15) NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `FilmIformation_idFilmIformation` INT NOT NULL,
  PRIMARY KEY (`idPayments`, `Clients_idClients`, `FilmIformation_idFilmIformation`),
  CONSTRAINT `fk_Payments_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `Film_Base`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payments_FilmIformation1`
    FOREIGN KEY (`FilmIformation_idFilmIformation`)
    REFERENCES `Film_Base`.`FilmIformation` (`idFilmIformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Film_Base`.`Films_Loues_has_Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`Films_Loues_has_Clients` (
  `Films_Loues_idIntermediaire_table` INT NOT NULL,
  `Clients_idClients` INT NOT NULL,
  PRIMARY KEY (`Films_Loues_idIntermediaire_table`, `Clients_idClients`),
  CONSTRAINT `fk_Films_Loues_has_Clients_Films_Loues1`
    FOREIGN KEY (`Films_Loues_idIntermediaire_table`)
    REFERENCES `Film_Base`.`Films_Loues` (`idIntermediaire_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Films_Loues_has_Clients_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `Film_Base`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Film_Base`.`Films_Loues_has_FilmIformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Film_Base`.`Films_Loues_has_FilmIformation` (
  `Films_Loues_idIntermediaire_table` INT NOT NULL,
  `FilmIformation_idFilmIformation` INT NOT NULL,
  PRIMARY KEY (`Films_Loues_idIntermediaire_table`, `FilmIformation_idFilmIformation`),
  CONSTRAINT `fk_Films_Loues_has_FilmIformation_Films_Loues1`
    FOREIGN KEY (`Films_Loues_idIntermediaire_table`)
    REFERENCES `Film_Base`.`Films_Loues` (`idIntermediaire_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Films_Loues_has_FilmIformation_FilmIformation1`
    FOREIGN KEY (`FilmIformation_idFilmIformation`)
    REFERENCES `Film_Base`.`FilmIformation` (`idFilmIformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
